name: secure_flutter_app
description: A highly secure Flutter application with comprehensive security features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # تشفير وأمان
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  jwt_decoder: ^2.0.1
  dartz:

  # مصادقة وتفويض
  local_auth: ^2.1.7
  flutter_keychain: ^2.4.0
  biometric_storage: ^5.0.0+1

  # شبكات واتصالات
  dio: ^5.3.3
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  flutter_windowmanager: ^0.2.0

  # كشف الجذر والجيلبريك
  flutter_jailbreak_detection: ^1.10.0
  safe_device: ^1.1.4
  flutter_root_jailbreak: ^2.0.2

  # إدارة الحالة
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # حقن التبعيات
  get_it: ^7.6.4
  injectable: ^2.3.0

  # معلومات الجهاز
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

  # الصور والتحميل
  cached_network_image: ^3.3.0
  pinch_zoom: ^2.0.0

  # مساعدات عامة
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.5

  # تسجيل وتحليل الأخطاء
  logger: ^2.0.2+1
 # flutter_secure_logger: ^1.0.3

  # تحسينات واجهة المستخدم
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # حماية الشاشة
#  flutter_screenprotector: ^1.2.0
  disable_screenshots: ^0.2.0

  # تعتيم الكود
  #flutter_obfuscation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/certificates/
    - assets/configs/

